services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ./volumes/ollama:${OLLAMA_DATA_PATH}
      - models:${OLLAMA_MODELS_PATH}

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT}:8080"
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - OLLAMA_WEBUI_EMAIL=${OLLAMA_WEBUI_EMAIL}
      - OLLAMA_WEBUI_PASSWORD=${OLLAMA_WEBUI_PASSWORD}
      # Set JWT to expire in 24 hours (86400 seconds)
      - JWT_EXPIRES_IN=86400
    depends_on:
      - ollama
    volumes:
      - ./volumes/webui/data:/app/backend/data

volumes:
  models:
  ollama:
  webui:
